### ISSUE TITLE
Allow configuring RGB colour mode chroma and lightness

### ISSUE THREAD

**Issue by arzg** [CookieCoder15/pipes-rs#12]
This could result in invalid colours; I’ve come up with two possible solutions:

- before drawing anything on the screen you go through all possible hues, ensuring that they are all valid
- if the colour you generate is invalid, you then try again with a different random hue. This means you won’t definitely get an even mix of colours (you’ll only get those possible at the current chroma/lightness combination), and also would lead to an infinite loop if there aren’t any valid colours at that chroma and lightness

**Comment by arzg** [comment]
This all is probably overkill; instead we can just offer two presets for light and dark mode (if the current one looks bad in light mode).

**Comment by CookieCoder15** [comment]
Here are screenshots of pipes-rs running in RGB mode with Apple terminal default light and dark backgrounds:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/40507205/109594668-500fe900-7b67-11eb-9b64-41a1b53c650d.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/40507205/109594862-97967500-7b67-11eb-9f82-4445476e8d24.png">

Opinions?

**Comment by arzg** [comment]
I’d say that it’s worth adding an extra ‘pastel’ colour variant that has a higher brightness and lower chroma for people that use pastel themes (fairly common). The existing colours look good on light and dark, though; maybe it would be worth making a slightly darker version for light backgrounds though.
