### ISSUE TITLE
Build Linux, Windows and Mac binaries using CD workflow

### ISSUE THREAD

**Issue by CookieCoder15** [CookieCoder15/pipes-rs#17]
Currently CD only builds for macOS and publishes to the Homebrew tap. Support to publish a release of Windows, Linux and macOS binaries would be good.

**Comment by arzg** [comment]
Both Apple Silicon and x86? I think rust-analyser builds Apple Silicon binaries using GitHub Actions, but I’m not sure.

**Comment by CookieCoder15** [comment]
x86 is required, Apple Silicon is nice to have as pipes-rs runs fine through Rosetta 2

**Comment by arzg** [comment]
Fixed by a8c4092.
