### ISSUE TITLE
Seeing tofu instead of heavy, curved, knobby, emoji on windows 10

### ISSUE THREAD

**Issue by Droyk** [CookieCoder15/pipes-rs#46]
https://gfycat.com/heftyparallelannelid
~it keeps resetting! Am I doing something wrong? or this is a bug?
using this command
`pipes-rs.exe -b true -c rgb -i true -k curved -p 100`~

Seems like I don't have the required Character set to view the heavy, curved, knobby, emojis pipe faces on my system!

Edit: *curved instead of dots
Edit: I forgot to set the reset threshold! it was my fault! forgive me guys!

**Comment by arzg** [comment]
I think the rectangles are from your font not having the curved corner characters. What do you mean with ‘doesn’t loop’?

**Comment by CookieCoder15** [comment]
> Doesn't loop

Could you elaborate on this? I'm not too sure what you mean. I can see the screen resetting just fine in the gif you attached.

> seeing rectangles instead of curved face on windows 10

Attached below is a photo of what the dotted pipes usually look like, the change in appearance is perhaps a windows bug as @arzg and I both develop on macOS. I will test on Linux and Windows shortly, looks like some form of bug.

![Dots pipe type](https://user-images.githubusercontent.com/40507205/110076239-450fbf80-7dd8-11eb-9f89-0476f5948287.gif)

**Comment by arzg** [comment]
> windows bug

I think it’s more likely that the font @Droyk is using doesn’t have the required curved corner characters, so Windows displays them as [tofu](https://en.wikipedia.org/wiki/Noto_fonts#Etymology).

**Comment by CookieCoder15** [comment]
@Droyk did you mean to do the dots type or the curved type in the command? The title and gif would suggest you were using the curved pipe type but your provided command uses dots.

**Comment by Droyk** [comment]
>@CookieCoder15 Could you elaborate on this? I'm not too sure what you mean. I can see the screen resetting just fine in the gif you attached.

~I thought it would just keep going on & it wouldn't reset & I thought that was a bug but now in the gif you submitted it seems like this is how you wanted it to work. is there is any way to make this work without reset coz otherwise it's quite how to say this "unsatisfying"!~ forgive me I forgot to set the reset threshold that was the reason it was keep resetting I thought it was bug that doesn't let me run it infinitely.

>@arzg I think it’s more likely that the font @Droyk is using doesn’t have the required curved corner characters, so Windows displays them as tofu.

So which font set or character set should I download to get this curved face?

>@CookieCoder15  did you mean to do the dots type or the curved type in the command? The title and gif would suggest you were using the curved pipe type but your provided command uses dots.

forgive me for the confusion, my main problems were I keep seeing tofu's on heavy, curved, knobby, emoji pipe faces & forget to set the reset threshold so thought this is a bug on windows that can't let me run the pipes infinitely. stupid me 

Forgive me 😅🙏

**Comment by arzg** [comment]
I’m not sure what fonts could work, but Noto Mono might be good (Noto is short for ‘no tofu’; the font’s entire purpose is to have so many characters as to eliminate tofu).

**Comment by CookieCoder15** [comment]
Added disclaimer about windows font issue to the readme and suggested alternate font recommended by @arzg. Closing this issue now, if more issues appear please reopen or create a new issue. I am happy to look into any other suggestions for windows font issue fixes as well.
